name: chloride-dynamics-io-neuron
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - jupyter
  - matplotlib
  - numpy
  - seaborn
  - colorlog
  - neuron
  - gxx_linux-64
  - h5py
prefix: C:\Users\Chris\Anaconda3\envs\chloride-dynamics-io-neuron
